remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: Neha Malhotra
description: Personal website of Neha Malhotra

plugins:
  - jekyll-sitemap

navigation:
- name: Home
  link: ./
- name: Projects
  link: ./projects.html
