# _config.yml

title: My Awesome Website    
description: Welcome to my GitHub Pages site
theme: minima                
author:                      
  name: Neha Malhotra
  email:neha.malhotra@berkeleyedu
baseurl: ""                  
url: "https://ahen22.github.io"  

# Build settings
markdown: kramdown           

